Importing
addFields
  reader
    recordClass: Dictionary;
    addFieldAt: #'ayca';
    addFieldAt: #'designAssignedTo';
    addFieldAt: #'designAssignmentDate';
    addFieldAt: #'designETA';
    addFieldAt: #'sam';
    addFieldAt: #'buildType';
    addFieldAt: #'buildSubType';
    addFieldAt: #'designSowReceivedDate';
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addFieldAt: #'designDDDSubmissionForecastDate';
    addFieldAt: #'designDDDActualSubmissionDate';
    addFieldAt: #'designDDDResubmissionDate';
    addFieldAt: #'designStatus';
    addFieldAt: #'designDDDApprovedDate';
    addFieldAt: #'designLAANSubmissionDate';
    addFieldAt: #'designHECSubmissionDate';
    addFieldAt: #'designHECApprovalDate';
    addFieldAt: #'designLAANStartDate';
    addFieldAt: #'designNotes';
    addIgnoredField