Importing
addFields
  reader
    recordClass: Dictionary;
    addFieldAt: #'ayca';
    addFieldAt: #'designAssignedTo';
    addFieldAt: #'designAssignmentDate';
    addFieldAt: #'designETADate';
    addFieldAt: #'designStatus';
    addFieldAt: #'sam';
    addFieldAt: #'buildType';
    addFieldAt: #'buildSubType';
    addFieldAt: #'designSowReceivedDate';
    addFieldAt: #'designGMLSubmissionDate';
    addFieldAt: #'designPONPatchingRequestDate';
    addFieldAt: #'designPONSOWReceivedDate';
    addFieldAt: #'designDDDSubmissionForecastDate';
    addFieldAt: #'designDDDActualSubmissionDate';
    addFieldAt: #'designDDDResubmissionDate';
    addFieldAt: #'designDDDStatus';
    addFieldAt: #'designDDDApprovedDate';
    addFieldAt: #'designLAANSubmissionDate';
    addFieldAt: #'designHECSubmissionDate';
    addFieldAt: #'designHECApprovalDate';
    addFieldAt: #'designLAANStartDate';
    addFieldAt: #'designNotes';
    addFieldAt: #'designNBNComments'