Importing
addFields
  reader
    recordClass: Dictionary;
    addFieldAt: #'ayca';
    addFieldAt: #'address';
    addFieldAt: #'constructionProjectType';
    addFieldAt: #'constructionBuildType';
    addFieldAt: #'sam';
    addFieldAt: #'clientContact';
    addFieldAt: #'efscdDate';
    addIgnoredField;
    addFieldAt: #'constructionProjectLead';
    addFieldAt: #'constructionStatus';
    addFieldAt: #'constructionSiteContact';
    addFieldAt: #'constructionLeadInReady';
    addFieldAt: #'constructionCommsRoomReady';
    addFieldAt: #'constructionInternalPathwayReady';
    addFieldAt: #'constructionTestAndCoiled';
    addFieldAt: #'constructionLAANCommenceDate';
    addFieldAt: #'constructionDesignForecastSubmissionDate';
    addFieldAt: #'constructionDesignActualSubmissionDate';
    addFieldAt: #'constructionForecastStartDate';
    addFieldAt: #'constructionActualStartDate';
    addFieldAt: #'constructionForecastCompleteDate';
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addFieldAt: #'constructionActualCompleteDate';
    addIgnoredField;
    addFieldAt: #'constructionFollowUpDate';
    addFieldAt: #'constructionComments';
    addFieldAt: #'constructionForecastPCSubmitDate';
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addIgnoredField;
    addFieldAt: #'constructionActualPCSubmitDate';
    addIgnoredField;
    addIgnoredField