Importing
addFields
  reader
    recordClass: Dictionary;
    addFieldAt: #'Contractor';
    addFieldAt: #'Job Title';
    addFieldAt: #'Address';
    addFieldAt: #'SAM';
    addFieldAt: #'Due Completion';
    addFieldAt: #'ADA';
    addFieldAt: #'State';
    addFieldAt: #'Comment';
    addFieldAt: #'Delivery Partner';
    addFieldAt: #'Job Completion Date';
    addFieldAt: #'LOC-ID valid-Y/N';
    addFieldAt: #'Photo';
    addFieldAt: #'Leadin Available';
    addFieldAt: #'Leadin Cut_in';
    addFieldAt: #'Lead-in Length >150';
    addFieldAt: #'MDU>19';
    addFieldAt: #'Number of LOCs';
    addFieldAt: #'DPU port capacity ';
    addFieldAt: #'DPU within EPR Zone';
    addFieldAt: #'DPU number ';
    addFieldAt: #'Port Number ';
    addFieldAt: #'PNI Uplift ';
    addFieldAt: #'LOC-ID-Tech type-FTTC/FTTB/Other ';
    addFieldAt: #'Bespoke Design Solution';
    addFieldAt: #'Contractor';
    addFieldAt: #'Job Due Date';
    addFieldAt: #'Solution'