Importing
addFields20190520
  reader
    recordClass: Dictionary;
    addFieldAt: #'contract';
    addFieldAt: #'projectName';
    addFieldAt: #'location';
    addFieldAt: #'projectEngineer';
    addFieldAt: #'invoiceNumber';
    addFieldAt: #'invoiceCreatedDate';
    addFieldAt: #'projectCompletionsHandedOverDate';
    addFieldAt: #'pcRequestSubmittedDate';
    addFieldAt: #'variationRequestSubmittedDate';
    addFieldAt: #'variationApprovedDate';
    addFieldAt: #'pcDueDate';
    addFieldAt: #'paymentDate';
    addFieldAt: #'monthClaimed';
    addFieldAt: #'actualPaymentDate';
    addFieldAt: #'maximoOrderNumber';
    addFieldAt: #'fsamMps';
    addFieldAt: #'suburb';
    addFieldAt: #'cspoAmount';
    addFieldAt: #'variation';
    addFieldAt: #'totalRevenue';
    addFieldAt: #'gstInc';
    addFieldAt: #'djcCost';
    addFieldAt: #'internalDjcCost';
    addFieldAt: #'totalCost';
    addFieldAt: #'margin';
    addFieldAt: #'percentage';
    addFieldAt: #'nbnContact';
    addFieldAt: #'projectQuoteSubmittedDate';
    addFieldAt: #'projectAwardedDate';
    addFieldAt: #'daysToAward';
    addFieldAt: #'customerRequiredDate';
    addFieldAt: #'differenceRequiredToAwardDate'