export file
headerRow
  ^ {'Request ID'.
  'Job Owner/Assigned To'.
  'Assigned Date'.
  'ETA'.
  'STATUS'.
  'SAM ID'.
  'Build Type'.
  'Type'.
  'SOW Received Date'.
  '10.1.1 GML Submission Date'.
  'PON Patching Request Date'.
  'PON SOW Received Date'.
  'DDD Submission Forecast Date'.
  'DDD Actual Submission Date'.
  'DDD Resubmission Date'.
  'DDD Status'.
  'DDD Approved Date'.
  'LAAN SubmissionDate'.
  'HECS ubmissionDate'.
  'HEC ApprovalDate'.
  'LAAN Start'.
  'DP Comments'.
  'NBN Comments'}