export file
addFieldsToWriter: csvWriter
  csvWriter
    addField: #'aycaNumber';
    addField: #'address';
    addField: #'constructionProjectType';
    addField: #'constructionBuildType';
    addField: #'sam';
    addField: #'clientContact';
    addField: #'efscdDate';
    addEmptyField;
    addField: #'constructionProjectLead';
    addField: #'constructionStatus';
    addField: #'constructionSiteContact';
    addField: #'constructionLeadInReady';
    addField: #'constructionCommsRoomReady';
    addField: #'constructionInternalPathwayReady';
    addField: #'constructionTestAndCoiled';
    addField: #'constructionLAANCommenceDate';
    addField: #'constructionDesignForecastSubmissionDate';
    addField: #'constructionDesignActualSubmissionDate';
    addField: #'constructionForecastStartDate';
    addField: #'constructionActualStartDate';
    addField: #'constructionForecastCompleteDate';
    addEmptyField;
    addEmptyField;
    addEmptyField;
    addEmptyField;
    addField: #'constructionActualCompleteDate';
    addEmptyField;
    addField: #'constructionFollowUpDate';
    addField: #'constructionComments';
    addField: #'constructionForecastPCSubmitDate'