export file
headerRow
  | headerRow |
  headerRow := {'RequestID'.
  'Application Name'.
  'Project Type'.
  'Build Type'.
  'FSAM'.
  'NBN PM'.
  'EFSCD'.
  'EFSCD by Month'.
  'Project Leader'.
  'Project Status'.
  'Site Contact'.
  'LAAN Commence'.
  'FORECAST DESIGN SUBMISSION'.
  'ACTUAL DESIGN SUBMISSION'.
  'FORECAST CONSTRUCTION START'.
  'ACTUAL CONSTRUCTION START'.
  'FORECAST: CONSTRUCTION COMPLETE'.
  'ACTUAL: CONSTRUCTION COMPLETE'.
  'Actual: Construction Complete by Month'.
  'Follow up Date'.
  'Comments:'}.
  ^ headerRow