setup
installDatateksRateCards
  (NWRateCard
    fromRateCardCSVFileOnPath:
      '/opt/git/MyNationEarth/NetWorks/testResources/Metro Combined Rates.csv')
    title: 'A417 New Devs Metro Rate Card 2018';
    startDate: Date today;
    import.
  (NWRateCard
    fromRateCardCSVFileOnPath:
      '/opt/git/MyNationEarth/NetWorks/testResources/Regional Combined Rates.csv')
    title: 'A417 New Devs Regional Rate Card 2018';
    startDate: Date today;
    import