5smiths
xeroContractorData
  ^ {{'75101'.
  'Subcontractor - Andrew Martin'.
  ''.
  '70%'}.
  {'75102'.
  'Subcontractor - Apex Domain'.
  '75102-00017'.
  '70%'}.
  {'75103'.
  'Subcontractor - Wayne Hagar'.
  ''.
  '70%'}.
  {'75104'.
  'Subcontractor - Jablonka'.
  '75104-00052'.
  '70%'}.
  {'75105'.
  'Subcontractor - Mark Rodier'.
  '75105-00042'.
  '70%'}.
  {'75106'.
  'Subcontractor - Madison Rodier'.
  '75106-00044'.
  '70%'}.
  {'75107'.
  'Subcontractor - Matt DeMarco'.
  ''.
  '70%'}.
  {'75108'.
  'Subcontractor - Jack Brown'.
  ''.
  '70%'}.
  {'75109'.
  'Subcontractor - Abilash Mulakkamparambath'.
  ''.
  '70%'}.
  {'75110'.
  'Subcontractor - Phil Plesko'.
  ''.
  '70%'}.
  {'75111'.
  'Subcontractor - Today Job Services'.
  '75111-00102'.
  '70%'}.
  {'75112'.
  'Subcontractor - Steve Spiteri'.
  '75112-00091'.
  '80%'}.
  {'75113'.
  'Subcontractor - RudiComm'.
  '75113-00055'.
  '70%'}.
  {'75114'.
  'Subcontractor - Carry on Designing'.
  '75114-00070'.
  '70%'}.
  {'75115'.
  'Subcontractor - Digital Data'.
  '75115-00017'.
  '70%'}.
  {'75116'.
  'Subcontractor - Apex Comms'.
  '75116-00009'.
  '70%'}.
  {'75117'.
  'Subcontractor - Glen Turner'.
  ''.
  '70%'}.
  {'75118'.
  'Subcontractor - Ell-Corp'.
  '75118-00046'.
  '70%'}.
  {'75119'.
  'Subcontractor - Edgeline'.
  '75119-00003'.
  '70%'}.
  {'75120'.
  'Subcontractor - Carney Comms'.
  '75120-00007'.
  '70%'}.
  {'75121'.
  'Subcontractor - Hitech'.
  '75121-00036'.
  '70%'}.
  {'75122'.
  'Subcontractor - Socorp'.
  '75122-00020'.
  '70%'}.
  {'75123'.
  'Subcontractor - Leone Corp Pty Ltd'.
  '75123-00003'.
  '70%'}.
  {'75124'.
  'Subcontractor - Traffic Worx'.
  '75124-00010'.
  '70%'}.
  {'75125'.
  'Subcontractor - Pinnacle Excavations'.
  '75125-00010'.
  '90%'}.
  {'75126'.
  'Subcontractor - Kim Communications'.
  '75126-00019'.
  '80%'}.
  {'75127'.
  'Subcontractor - TEK Communications'.
  '75127-00038'.
  '70%'}.
  {'75128'.
  'Subcontractor - CKLJ Comms and Services'.
  ''.
  '70%'}.
  {'75129'.
  'Subcontractor - Thomas Grieve'.
  ''.
  '70%'}.
  {'75130'.
  'Subcontractor - AJCLEMM Services'.
  ''.
  '70%'}.
  {'75131'.
  'Subcontractor - Andrew Bede Services'.
  ''.
  '70%'}.
  {'75132'.
  'Subcontractor - QUBiCON Group'.
  ''.
  '70%'}.
  {'75133'.
  'Subcontractor - Tracey Hagar'.
  ''.
  '70%'}.
  {'75134'.
  'Subcontractor - Transcom Services'.
  '75134-00006'.
  '70%'}.
  {'75135'.
  'Subcontractor - O.S. Cable Services'.
  ''.
  '70%'}.
  {'75136'.
  'Subcontractor - Crawford Communications Aust'.
  ''.
  '70%'}.
  {'75137'.
  'Subcontractor - P A Blake'.
  ''.
  '70%'}.
  {'75138'.
  'Subcontractor - Superb Cabling'.
  ''.
  '70%'}.
  {'75140'.
  'Subcontractor - Today Job Services Labour Hire'.
  '75140-00027'.
  '70%'}.
  {'75141'.
  'Subcontractor - SMY Operations Pty Ltd'.
  '75141-00003'.
  '70%'}.
  {'75142'.
  'Subcontractor - Tonagh Civil Pty Ltd'.
  '75142-00001'.
  '70%'}.
  {'75143'.
  'Subcontractor - KJP Comms Pty Ltd'.
  '75143-00009'.
  '80%'}.
  {'75144'.
  'Subcontractor - Coops Beau Pty Ltd'.
  '75144-000021'.
  '80%'}.
  {'75145'.
  'Subcontractor - Wolfcon'.
  ''.
  '70%'}.
  {'75146'.
  'Subcontractor - Jibtech Pty Ltd'.
  '75146-00005'.
  '70%'}}