Importing
addFields
  reader
    recordClass: Dictionary;
    addFieldAt: #'technology';
    addFieldAt: #'deliveryPartnerName';
    addFieldAt: #'locationSuburb';
    addFieldAt: #'locationState';
    addFieldAt: #'materialTitle';
    addFieldAt: #'materialComment';
    addFieldAt: #'materialUnitOfMeasure';
    addFieldAt: #'quantity';
    addFieldAt: #'faultyQuantity';
    addFieldAt: #'reportDate'