export file
headerRow
  ^ {'Contract'.
  'Location'.
  'PE'.
  'Inv No.'.
  'Date Invoice Created'.
  'Date Project Completions handed over'.
  'PC Request Date Submitted'.
  'Variation Request submitted'.
  'Variation Approval'.
  'Project Awarded Date'.
  'Payment Date'.
  'EFSCD Date'.
  'Project Description'.
  'Suburb'.
  'CSPO Amount'.
  'Variation'.
  'Total Revenue'.
  'DJC Cost'.
  'Internal Design Cost'.
  'Internal Construction Cost'.
  'Total Cost'.
  'Margin'.
  '%'.
  'Status'.
  'NBN PO/PM'.
  'Advance Payment'.
  'Advance Payment Date'.
  'Final Payment'}