export file
headerRow
  ^ {'Contract'.
  'Location'.
  'PE'.
  'Inv No.'.
  'Date Invoice Created'.
  'Date Project Completions handed over'.
  'PC Request Date Submitted'.
  'Variation Request submitted'.
  'Variation Approval'.
  'PC Due'.
  'Payment Date'.
  'Actual Payment Date'.
  'Project Description'.
  'Suburb'.
  'CSPO Amount'.
  'Variation'.
  'Total Revenue'.
  'GST Inc'.
  'DJC Cost'.
  'Internal DJC Cost'.
  'Total Cost'.
  'Margin'.
  '%'.
  'Status'.
  'NBN PO/PM'.
  'Advance Payment'.
  'Advance Payment Date'}