export file
headerRow
  ^ {'Contract'.
  'Location'.
  'PE'.
  'Inv No.'.
  'Date Invoice Created'.
  'Date Project Completions handed over'.
  'PC Request Date Submitted'.
  'Variation Request submitted'.
  'Variation Approval'.
  'PC Due'.
  'Payment Date'.
  'PC, Variation & Payment Comments'.
  'Month Claimed'.
  'Actual Payment Date'.
  'Project Description'.
  'Suburb'.
  'CSPO Amount'.
  'Variation'.
  'Total Revenue'.
  'GST Inc'.
  'DJC Cost'.
  'Internal DJC Cost'.
  'Total Cost'.
  'Margin'.
  '%'.
  'Status'.
  'NBN PO/PM'.
  'Project Quote Submitted'.
  'Project Award Date'.
  'Days to Award'.
  'Customer required date'.
  'Difference CRD to Award'}