Importing
addFields2
  reader
    recordClass: Dictionary;
    addFieldAt: #'ayca';
    addFieldAt: #'sam';
    addFieldAt: #'buildType';
    addFieldAt: #'buildSubType';
    addFieldAt: #'designSowReceivedDate';
    addFieldAt: #'designDDDForecastSubmissionDate';
    addFieldAt: #'designDDDActualSubmissionDate';
    addFieldAt: #'designDDDResubmissionDate';
    addFieldAt: #'designStatus';
    addFieldAt: #'designDDDApprovedDate';
    addFieldAt: #'designLAANSubmissionDate';
    addFieldAt: #'designHECSubmissionDate';
    addFieldAt: #'designHECApprovalDate';
    addFieldAt: #'designLAANStartDate';
    addFieldAt: #'designNotes'